# Numpy

- NumPy stands for Numerical Python
- It is an open-source Python library used for fast numerical computation
- It is used to work with multi-dimensional array.
- Unlike Python list, Numpy is designed to peform mathematical operation and scientific calculation.
- Official name of Numpy is Numerical Python, developed by Travis Oliphant in 2005.

## Why numpy was created :

- Before numpy programmer uses list to store number, it works well for basis task, but become slow when working with large dataset.

using python lists would :

- Consume more memory..
- Execute calculations more slowly..
- Require explicit loops for most operations..

NumPy solves these problem by using highly optimized array structure..

## Command to download numpy library :

- Open terminal or command prompt and run below command :
- pip install numpy

#### Advantage :

- Faster Execution
- Less Memory Usage
- Multi-Dimensional Arrays
- Easy Mathematical Operations
- less amount of code

## Why do we need Numpy?

In [ ]:
l =[10,20,30,40,50]
for i in range(len(l)):
    # print(l[i])
    l[i] = l[i] + 5

print(l)

[15, 25, 35, 45, 55]


In [ ]:
# importing Numpy package
import numpy as np

In [ ]:
marks = np.array([10,20,30,40,50])
print(marks+5) # This is called vectorized computation, where operations are applied to every element of a array automatically.

[15 25 35 45 55]


# Mathematical operations :

- sum()
- mean()
- median()
- sqrt()
- log()
- exp()
- sin()
- cos()
- max()
- min()

## Where is Numpy Used :

- Data Science
- Machine Learning..
- Artifical Intelligence.
- Image Processing.
- Scientific Computing.

In [ ]:
# First program of numpy :
import numpy as np

l = [1,2,3,4,5]
data = np.array(l) # np.array converts list into numpy array
print(type(l))
print(type(data)) #ndarray

<class 'list'>
<class 'numpy.ndarray'>


# Numpy Array :

- A Numpy Array is a core data str. provided by Numpy
- It a collection of elements with similar data type.
- Stored in contiguous memory location, which makes operations on data much faster
- The class used by Numpy is known as ndarray, which stands for N-dimensional array.
- N means any number of dimensions.
- Array can be 1D,2D,3D or even more dimensional..

In [11]:
import numpy as np

marks = np.array([10,20,30,40,50])
print(marks)

[10 20 30 40 50]


In [12]:
# creating array of string data type
names = np.array(['Suhani',"Anukul","Sarika Maam","HOD Sir"])
print(names)
print(type(names))

['Suhani' 'Anukul' 'Sarika Maam' 'HOD Sir']
<class 'numpy.ndarray'>


In [13]:
# Creating array of float data type

price = np.array([2.2,3.3,4.4,5.5,6.6])
print(type(price))
print(price)

<class 'numpy.ndarray'>
[2.2 3.3 4.4 5.5 6.6]


In [16]:
x = np.array([1,2,2.2,4,5])
print(x)
print(type(x))

[1.  2.  2.2 4.  5. ]
<class 'numpy.ndarray'>


In [17]:
y = np.array([1,2,"Suhani",2.2])
print(y)
print(type(y))

['1' '2' 'Suhani' '2.2']
<class 'numpy.ndarray'>


In [18]:
# one Dimensional Array:  A 1D array is like a single row

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
# Two Dimensional Array(2D) : A 2D array has row and column
l = [[1,2,3],[4,5,6]]
n = np.array(l)
print(n)

[[1 2 3]
 [4 5 6]]


## Representation of 3D array
    a = np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
    ])

layer 0 : 
    Row 0 : [1,2]
    Row 1 : [3,4]
layer 1:
    Row 0 : [5,6]
    Row 1 : [7,8]

In [ ]:
# Three-Dimensional Array(3D): A 3D is a collection multiple 2D array.
'''
indexing format for 3D array :

array[layer][row][column]
'''

a = np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Indexing in Array:

- Indexing allows us to access individual elements..
- Indexing starts from 0
- In numpy array also both types of indexing follows +ve and -ve..

In [22]:
a = np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
])
print(a[0][1][1])

4


#  Numpy Array Properties :

- By using these properties we can find the info of numpy array..
    * ndim
    * shape
    * size
    * dtype
    * itemsize
    * nbytes

In [23]:
# ndim : returns number of dimensions of array
a = np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
])
a.ndim

3

In [25]:
l = np.array([[1,2,3],[4,5,6]])
l.ndim

2

In [26]:
# shape : returns number of elements along each dimension
l.shape

(2, 3)

In [27]:
# size : it returns total number of element in an array
l.size

6

In [28]:
# dtype : returns data type of elements..

l.dtype

dtype('int64')

In [33]:
t = np.array([True,False])
print(t.dtype)
print(t.itemsize)

bool
1


In [ ]:
a =np.array(['A',"B","C"])
a.dtype # this will return <U1 : U - Unicode String , 1 - maximum length is 1 character.

dtype('<U1')

In [31]:
# itemsize : tells how many bytes one element is taking

n= np.array([1,2,3,4,5,6,7])
n.itemsize

8

In [34]:
# nbytes : returns total memory occupied by an array
n= np.array([1,2,3,4,5,6,7])
n.nbytes

56